# Generated by Django 4.2 on 2023-05-01 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_author_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='last_changes',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Последнее изменение'),
            preserve_default=False,
        ),
    ]
