# Generated by Django 4.2 on 2023-05-01 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_remove_post_title_post_last_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_changes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='Lorem epsum', verbose_name='Tекст'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Lorem epsum', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
