# Generated by Django 4.2 on 2023-05-01 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_created_at_remove_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, verbose_name='<django.db.models.fields.DateTimeField>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.CharField(default=django.utils.timezone.now, verbose_name='<django.db.models.fields.DateTimeField>'),
            preserve_default=False,
        ),
    ]
