# Generated by Django 4.2 on 2023-05-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_created_at_remove_post_updated_at'),
    ]

    operations = [
    ]
