# Generated by Django 4.2 on 2023-05-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20230502_0445'),
    ]

    operations = [
    ]
